name: build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - run: cmake -B build
      - run: cmake --build build --config Release

      - uses: softprops/action-gh-release@v2
        if: ${{ github.event_name != 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/Release/brightness.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - env:
          CREATE_INFOPLIST_SECTION_IN_BINARY: YES
          GENERATE_INFOPLIST_FILE: YES
          INFOPLIST_KEY_CFBundleIdentifier: com.user.brightness
          INFOPLIST_KEY_CFBundlePackageType: APPL
          INFOPLIST_KEY_LSUIElement: YES
          OTHER_SWIFT_FLAGS: -parse-as-library
        run: xcodebuild -scheme brightness -configuration Release -derivedDataPath .build -destination "platform=macOS"

      - run: |
          mkdir -p brightness.app/Contents/MacOS
          cp .build/Build/Products/Release/brightness brightness.app/Contents/MacOS/brightness
          cp Info.plist brightness.app/Contents/Info.plist

      - run: |
          mkdir bundle
          mv brightness.app bundle/brightness.app
          ditto -c -k --sequesterRsrc bundle brightness.app.zip

      - uses: softprops/action-gh-release@v2
        if: ${{ github.event_name != 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: brightness.app.zip
